name: Capture GithubAction Workflow status to Readme
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Githubaction Generator
        uses: GirishCodeAlchemy/githubaction-workflow-status-capture@v2.0